name: ChatOps in Issue Comment
# https://github.com/actions/github-script

on:
  issue_comment: 
    types: [created, edited]
jobs:
  chatops-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the full event webhook payload.
        env:
          GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}
          GITHUB_CONTEXT_EVENT_ISSUE: ${{ toJson(github.event.issue) }}
        run: |
          echo "GITHUB_CONTEXT_EVENT ${GITHUB_CONTEXT_EVENT}"
          echo "GITHUB_CONTEXT_EVENT_ISSUE ${GITHUB_CONTEXT_EVENT_ISSUE}"
      - name: ChatOps to apply a label to an issue
        if: contains(github.event.comment.body, '/triage')
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
      - name: Get assignee from comment body
        id: get-assignee
        run: |
          echo "The comment was: $(jq --raw-output .comment.body '${{ github.event_path }}')"
          comment_body=$(jq --raw-output .comment.body '${{ github.event_path }}')
          assignee=$(echo $comment_body \
            | awk 'match($0, /\/assign @[A-z\d-]{0,38}/) {print substr($0, RSTART, RLENGTH)}' \
            | awk '{name=substr( $2, index( $2, "@") + 1);print name}' )
          echo ::set-output name=assignee::$assignee
        if: contains(github.event.comment.body, '/assign')
      - name: ChatOps to assign user to the issue
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['${{steps.get-assignee.outputs.assignee}}']
            })
        if: steps.get-assignee.outputs.assignee != ''
