name: "Created from Release PR"
on:
  pull_request:
    branches:
      - "release"
    types: [closed]
  push:
    branches:
      - 'master'

#
# 動きとしてはこんなかんじ
# - git-pr-releaseはすべての更新をpushで行う
#   一番最初のPRをつくるpush　
#     この場合まだ、prが作られていない段階なので、PRが取得できず find-pull-request-actionでPR numが取得できない
#   - 2回目以降のpushでは既にPRが作られているので問題なし
jobs:
  release_workflow:
    runs-on: ubuntu-latest
    steps:
     - name: "find-pull-request"
       uses: juliangruber/find-pull-request-action@v1
       id: find-pull-request
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         branch: master
         base: release
     - name: "PR comment on Updating CFn Change Set"
       if: steps.find-pull-request.outputs.number
       uses: marocchino/sticky-pull-request-comment@v1
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         number: ${{ steps.find-pull-request.outputs.number }}
         header: "header sticky pull request"
         message: |
          Hello Hello Hello AFTER
     - name: "Wait 120 sec for PR create"
       #if: steps.find-pull-request.outputs.number == ''
       run: |
        echo "sleep 120"
        echo ${{ steps.find-pull-request.outputs.number }}
        sleep 120
     - name: "find-pull-request2"
       uses: juliangruber/find-pull-request-action@v1
       id: find-pull-request2
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         branch: master
         base: release
     - name: "After find-pull-request2"
       run: |
        echo ${{ steps.find-pull-request2.outputs.number }}

