name: Pull Request Workflow Cancel Example
on:
  pull_request:
    branches:
      - "master"
    types: [opened, synchronize, closed]

######## did not work ####################################
#jobs:
#  hello:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: khan/pull-request-workflow-cancel@1.0.0
#        with:
#          workflows: "pr-auto-cancel.yml"
#          #workflows: "example.yml | second.yml"
#        env:
#          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#      # Now do whatever other stuff
#      - uses: actions/checkout@v2
#      - run: echo 'Running now'
#      - run: sleep 40
#      - run: echo 'wasnt cancelled'


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      ####### worked!!!!
      - uses: styfle/cancel-workflow-action@0.5.0
        if: github.event.pull_request.merged != true
        with:
          access_token: ${{ github.token }}
      ####### did not work
      #- uses: fkirc/skip-duplicate-actions@master
      #  with:
      #    github_token: ${{ github.token }}
      # Now do whatever other stuff
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - run: echo 'Running now'
      - run: sleep 120
      - run: echo 'wasnt cancelled'
