on:
  push:
    branches:
      - test-action-setup-ecctl
jobs:
  test1: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yokawasa/action-setup-ecctl@v0.1.0
      with: 
        version: 'v1.0.0-beta2'
        # version: 'v1.0.0-beta3'
        # version: 'latest'
      id: setup
    - run: |
        ecctl=${{steps.setup.outputs.ecctl-path}}
        ${ecctl} version

  test2: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yokawasa/action-setup-ecctl@v0.1.0
      id: setup
    - run: |
        ecctl=${{steps.setup.outputs.ecctl-path}}
        ${ecctl} version



