name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yokawasa/action-setup-kube-tools@v0.1.0
      id: setup
    - run: |
        kubectl=${{steps.setup.outputs.kubectl-path}}
        kustomize=${{steps.setup.outputs.kustomize-path}}
        helm=${{steps.setup.outputs.helm-path}}
        helmv3=${{steps.setup.outputs.helmv3-path}}
        kubeval=${{steps.setup.outputs.kubeval-path}}
        conftest=${{steps.setup.outputs.conftest-path}}
        yq=${{steps.setup.outputs.yq-path}}

        ${kubectl} version --client
        ${kustomize} version
        ${helm} version --client
        ${helmv3} version 
        ${kubeval} --version 
        ${conftest} --version 
        ${yq} --version 

  test2: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yokawasa/action-setup-kube-tools@v0.1.0
      with: 
        kubectl: '1.17.1'
        kustomize: '3.7.0'
        helm: '2.16.7'
        helmv3: '3.2.4'
        kubeval: '0.14.0'
        conftest: '0.18.2'
      id: setup
    - run: |
        kubectl=${{steps.setup.outputs.kubectl-path}}
        kustomize=${{steps.setup.outputs.kustomize-path}}
        helm=${{steps.setup.outputs.helm-path}}
        helmv3=${{steps.setup.outputs.helmv3-path}}
        kubeval=${{steps.setup.outputs.kubeval-path}}
        conftest=${{steps.setup.outputs.conftest-path}}
        yq=${{steps.setup.outputs.yq-path}}

        ${kubectl} version --client
        ${kustomize} version
        ${helm} version --client
        ${helmv3} version 
        ${kubeval} --version 
        ${conftest} --version 
        ${yq} --version 

