name: sqlcheck workflow
on: pull_request


jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SQL Static Analysis with Sqlcheck
      uses: yokawasa/action-sqlcheck@v1.2.1
      #uses: yokawasa/action-sqlcheck@v1.2.0
      #uses: yokawasa/action-sqlcheck@v1.1.0
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
