name: Static analysis On PR

on:
  pull_request:
    types: [opened, synchronize]
    paths: '**.sh'

# shellcheck
# https://github.com/koalaman/shellcheck
#
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Check scripts with shellcheck
      env:
        EXCLUDE_OPTS: SC2086,SC2001
      run: |
        git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} \
          --diff-filter=AM \
          --name-only -- '*.sh' \
          | while read script ; do \
              shellcheck ${EXCLUDE_OPTS:+-e ${EXCLUDE_OPTS}} $script || \
              touch error.$$ ; \
            done
        test ! -e error.$$
