on:
  push:
    branches:
      - test-previous-job-status

## NOTE:
## Whether previous job fails/success, you always get job.status == success 
## in a job that matches always()condition.
## - always(): Always returns true, even when canceled. A job or step will not run when a critical failure prevents the task from running. 
## - failure(): Returns true when any previous step of a job fails.
## - success(): Returns true when none of the previous steps have failed or been canceled.
## 
## if you want to know previosu job status
## option1 - use technote-space/workflow-conclusion-action@v1
##   See https://github.com/marketplace/actions/workflow-conclusion-action
##   Internally the action use GitHub Workflow Job API
##   https://developer.github.com/v3/actions/workflow-jobs/
## option2 - Share job status across jobs using upload/download artifact
##   See https://github.community/t/how-get-the-status-of-previous-jobs/17555

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - run: exit 0
  two:
    runs-on: ubuntu-16.04
    needs: one
    steps:
      - run: exit 0

  three:
    runs-on: ubuntu-16.04
    needs: one
    steps:
      - run: exit 1

  test_always:
    # The job always starts running regardless of previous jobs' status (fail or success)
    if: always()
    needs:  [two,three]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "let's see previous job status"
          echo ${{ job.status }}
          # RESULT: job.status >>>> success 

  test_failure:
    # The job starts running only if previous jobs fail
    if: failure()
    needs:  [two,three]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "let's see previous job status"
          echo ${{ job.status }}
          # RESULT: job.status >>>> success 
 
  test_success:
    # The job starts running only if previous jobs succeed
    if: success()
    needs:  [two,three]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "let's see previous job status"
          echo ${{ job.status }}

  test_wf_conclusion_action:
    if: always()
    needs:  [two,three]
    runs-on: ubuntu-latest
    steps:
      # run this action to get workflow conclusion
      # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v1
      - run: |
          echo "let's see previous job status"
          echo ${{ env.WORKFLOW_CONCLUSION }}
